name: transformer_en_fa

channels:
  - pytorch
  - conda-forge
  - apple # Including apple channel for M1 compatibility
  - defaults

dependencies:
  - python=3.11.4
  - jupyter
  - numpy
  - scikit-learn
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - black
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - torchtext=0.15.2
  - datasets=2.15.0
  - tokenizers=0.13.3
  - torchmetrics=1.0.3
  - tensorboard=2.13.0
  - altair=5.1.1
  - wandb=0.15.9
  - pip:
      - openai
      - python-dotenv
      - langchain
      - docarray
      - tiktoken
      - chromadb
      - transformers
      - datasets
      - tensorboard

# For M1 Macs, use PyTorch's special build
platforms:
  - osx-arm64
